Repository ToKoSoftware/dhbw-svm-portal, pull requests merged in 2021-02, with the labels that each got.

#96 Backend: Create Api for Polls
  server/src/api/v2/poll-answer/create-poll-answer.ts
  server/src/api/v2/poll-vote/create-poll-vote.ts
  server/src/api/v2/polls/create-poll.ts
  server/src/functions/check-inputs.func.ts
  server/src/functions/map-poll-answer.func.ts
  server/src/functions/map-poll-vote.func.ts
  server/src/functions/map-polls.func.ts
  server/src/interfaces/poll-vote.interface.ts
  server/src/interfaces/poll.interface.ts
  server/src/migrations/20210124115053-fix-poll.js
  server/src/models/poll-answer.model.ts
  server/src/models/poll-vote.model.ts
  server/src/models/poll.model.ts
  server/src/server.ts
Labels: portal/backend

#112 Backend: Update Apis
  server/src/api/v2/events/update-event.ts
  server/src/api/v2/news/update-news.ts
  server/src/api/v2/organizations/update-organization.ts
  server/src/api/v2/poll-answers/create-poll-answer.ts
  server/src/api/v2/poll-answers/update-poll-answer.ts
  server/src/api/v2/poll-votes/create-poll-vote.ts
  server/src/api/v2/polls/update-poll.ts
  server/src/api/v2/roles/update-role.ts
  server/src/api/v2/teams/update-team.ts
  server/src/server.ts
Labels: portal/backend

#109 added delete-news
  server/src/api/v2/events/delete-event-registration.ts
  server/src/api/v2/events/delete-event.ts
  server/src/api/v2/news/delete-news.ts
  server/src/api/v2/poll-answers/delete-poll-answer.ts
  server/src/api/v2/poll-votes/delete-poll-vote.ts
  server/src/api/v2/polls/delete-poll.ts
  server/src/api/v2/roles/create-roles.ts
  server/src/api/v2/roles/create-roll-assignment.ts
  server/src/api/v2/roles/delete-role-assignment.ts
  server/src/api/v2/roles/delete-role.ts
  server/src/api/v2/teams/delete-membership.ts
  server/src/api/v2/teams/delete-team.ts
  server/src/functions/map-membership.func.ts
  server/src/functions/map-role-assignment.func.ts
  server/src/functions/map-roles.func.ts
  server/src/functions/map-teams.func.ts
  server/src/interfaces/role-assignment.interface.ts
  server/src/interfaces/role.interface.ts
  server/src/interfaces/team.interface.ts
  server/src/migrations/20210205221034-delete-is_active-from-Team-Role.js
  server/src/models/event.model.ts
  server/src/models/role-assignment.model.ts
  server/src/models/role.model.ts
  server/src/models/team.model.ts
  server/src/seeders/20210111120513-demo-data-set.js
  server/src/seeders/20210126145413-demo-not-admin.js
  server/src/server.ts
Labels: portal/backend

#135 changed Meeting Protocols to match md-standard
  documentation/meetings/2020-12-01.md
  documentation/meetings/2020-12-14.md
  documentation/meetings/2020-12-15.md
  documentation/meetings/2021-01-05.md
  documentation/meetings/2021-01-14.md
  documentation/meetings/2021-01-22.md
  documentation/meetings/2021-01-29.md
  documentation/meetings/2021-02-05.md
Labels: documentation

#128 Backend: Refactoring of userIsAdmin status
  server/src/api/v1/users/auth-user.ts
  server/src/api/v1/users/update-user.ts
  server/src/api/v2/events/delete-event-registration.ts
  server/src/api/v2/events/get-events.ts
  server/src/api/v2/news/delete-news.ts
  server/src/api/v2/news/get-news.ts
  server/src/api/v2/organizations/get-organizations.ts
  server/src/api/v2/poll-votes/delete-poll-vote.ts
  server/src/api/v2/polls/get-polls.ts
  server/src/api/v2/roles/get-roles.ts
  server/src/api/v2/teams/delete-membership.ts
  server/src/api/v2/teams/get-teams.ts
  server/src/functions/current-user-is-admin-or-matches-id.func.ts
  server/src/functions/jwt-sign.func.ts
  server/src/functions/user-is-admin-check.func.ts
  server/src/functions/verify-token.func.ts
  server/src/middleware/user-is-admin.middleware.ts
  server/src/migrations/20210208093101-delete-is-admin-column-from-users.js
  server/src/models/user.model.ts
  server/src/vars.ts
Labels: portal/backend

#133 Backend: Cleanup
  server/src/api/v1/users/create-user.ts
  server/src/api/v1/users/get-users.ts
  server/src/api/v1/users/update-user.ts
  server/src/api/v2/events/create-event.ts
  server/src/api/v2/events/delete-event-registration.ts
  server/src/api/v2/events/get-events.ts
  server/src/api/v2/events/update-event.ts
  server/src/api/v2/news/delete-news.ts
  server/src/api/v2/news/update-news.ts
  server/src/api/v2/organizations/get-organizations.ts
  server/src/api/v2/organizations/update-organization.ts
  server/src/api/v2/poll-answers/update-poll-answer.ts
  server/src/api/v2/poll-votes/delete-poll-vote.ts
  server/src/api/v2/polls/create-poll.ts
  server/src/api/v2/polls/delete-poll.ts
  server/src/api/v2/polls/get-polls.ts
  server/src/api/v2/polls/update-poll.ts
  server/src/api/v2/roles/create-role-assignment.ts
  server/src/api/v2/roles/get-roles.ts
  server/src/api/v2/roles/update-role.ts
  server/src/api/v2/teams/create-membership.ts
  server/src/api/v2/teams/create-team.ts
  server/src/api/v2/teams/delete-membership.ts
  server/src/api/v2/teams/delete-team.ts
  server/src/api/v2/teams/get-teams.ts
  server/src/api/v2/teams/update-team.ts
  server/src/functions/map-events.func.ts
  server/src/functions/verify-token.func.ts
  server/src/interfaces/event.interface.ts
  server/src/interfaces/news.interface.ts
  server/src/interfaces/poll.interface.ts
  server/src/interfaces/role.interface.ts
  server/src/interfaces/team.interface.ts
  server/src/models/event.model.ts
  server/src/models/organization.model.ts
  server/src/models/poll.model.ts
  server/src/models/role.model.ts
  server/src/models/team.model.ts
  server/src/server.ts
Labels: portal/backend

#146 * Fix register user ui
  frontend/src/app/login-register/register/register.component.html
  frontend/src/app/login-register/register/register.component.ts
Labels: portal/frontend

#149 Backend: Poll Api Adjustment
  server/src/api/v2/polls/get-polls.ts
  server/src/models/poll.model.ts
Labels: portal/backend

#147 Single Sign On
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/admin/overview/overview.component.html
  frontend/src/app/admin/overview/overview.component.ts
  frontend/src/app/app-routing.module.ts
  frontend/src/app/edit-create-pages/edit-create-pages.module.ts
  frontend/src/app/edit-create-pages/edit-developer-settings/edit-developer-settings.component.html
  frontend/src/app/edit-create-pages/edit-developer-settings/edit-developer-settings.component.ts
  frontend/src/app/icons/icons.module.ts
  frontend/src/app/login-register/login/login.component.ts
  frontend/src/app/sso/login/login.component.html
  frontend/src/app/sso/login/login.component.ts
  frontend/src/app/sso/sso.module.ts
  frontend/src/app/sso/sso.routes.ts
  frontend/src/app/ui/container/container.component.html
  frontend/src/app/ui/container/container.component.ts
  frontend/src/app/ui/input/input.component.ts
  frontend/src/app/ui/navbar/navbar.component.ts
  server/src/api/oauth2/authenticate.ts
  server/src/api/oauth2/configure.ts
  server/src/bootstrap/connect-db.func.ts
  server/src/functions/settings.func.ts
  server/src/interfaces/sso.interface.ts
  server/src/migrations/20210208161100-create-sso.js
  server/src/models/single-sign-on-request.model.ts
  server/src/models/user.model.ts
  server/src/server.ts
Labels: portal/backend, portal/frontend

#157 CHANGE: fixed README.md
  README.md
Labels: documentation

#154 Seeder demo data
  server/src/functions/random-time.func.js
  server/src/seeders/20210111120513-demo-data-set.js
  server/src/seeders/20210126145413-demo-not-admin.js
  server/src/seeders/20210209213654-demo-data.js
Labels: portal/backend

#153 Backend: Add missing APIs
  frontend/src/app/edit-create-pages/edit-user/edit-user.component.html
  frontend/src/app/edit-create-pages/edit-user/edit-user.component.ts
  server/src/api/v1/users/update-user.ts
  server/src/api/v2/event-registrations/delete-event-registration.ts
  server/src/api/v2/event-registrations/get-event-registrations.ts
  server/src/api/v2/event-registrations/register-for-event.ts
  server/src/api/v2/event-registrations/update-event-registration.ts
  server/src/api/v2/events/get-events.ts
  server/src/api/v2/news/get-news.ts
  server/src/api/v2/organizations/create-organization.ts
  server/src/api/v2/organizations/delete-organization.ts
  server/src/api/v2/organizations/get-organizations.ts
  server/src/api/v2/poll-answers/delete-poll-answer.ts
  server/src/api/v2/poll-votes/update-poll-vote.ts
  server/src/api/v2/polls/get-polls.ts
  server/src/api/v2/role-assignments/create-role-assignment.ts
  server/src/api/v2/role-assignments/delete-role-assignment.ts
  server/src/api/v2/roles/get-roles.ts
  server/src/api/v2/team-memberships/create-membership.ts
  server/src/api/v2/team-memberships/delete-membership.ts
  server/src/api/v2/teams/get-teams.ts
  server/src/functions/map-org.func.ts
  server/src/interfaces/organization.interface.ts
  server/src/migrations/20210210150000-update-org-access-code.js
  server/src/models/organization.model.ts
  server/src/models/poll-answer.model.ts
  server/src/models/user.model.ts
  server/src/server.ts
Labels: portal/backend

#158 Backend: Rechte
  server/src/api/v1/users/create-user.ts
  server/src/api/v1/users/get-users.ts
  server/src/api/v2/event-registrations/delete-event-registration.ts
  server/src/api/v2/poll-votes/create-poll-vote.ts
  server/src/api/v2/poll-votes/delete-poll-vote.ts
  server/src/api/v2/polls/delete-poll.ts
  server/src/api/v2/polls/get-polls.ts
  server/src/api/v2/team-memberships/delete-membership.ts
  server/src/api/v2/teams/get-teams.ts
  server/src/functions/verify-token.func.ts
  server/src/models/poll.model.ts
  server/src/models/team.model.ts
  server/src/server.ts
Labels: portal/backend

#164 Backend: DirectDebitMandate
  server/src/api/v2/direct-debit-mandate/create-direct-debit-mandate.ts
  server/src/api/v2/direct-debit-mandate/delete-direct-debit-mandate.ts
  server/src/api/v2/direct-debit-mandate/get-direct-debit-mandate.ts
  server/src/bootstrap/connect-db.func.ts
  server/src/functions/map-direct-debit-mandate.func.ts
  server/src/interfaces/direct-debit-mandate.interface.ts
  server/src/interfaces/organization.interface.ts
  server/src/migrations/20210213113535-direct-debit-mandate.js
  server/src/models/direct-debit-mandate.model.ts
  server/src/models/organization.model.ts
  server/src/models/user.model.ts
  server/src/server.ts
Labels: portal/backend

#163 backend: Datenschutzverordnung
  server/src/api/v1/users/create-user.ts
  server/src/api/v2/organizations/get-organization-by-access_code.ts
  server/src/interfaces/users.interface.ts
  server/src/server.ts
Labels: portal/backend

#168 Backend: Show expired Polls flag
  server/src/api/v2/polls/get-polls.ts
Labels: portal/backend

#167 Create User, Poll Vote, Poll Admin
  frontend/src/app/admin/admin.module.ts
  frontend/src/app/admin/admin.pages.ts
  frontend/src/app/admin/admin.routes.ts
  frontend/src/app/admin/overview/overview.component.html
  frontend/src/app/admin/overview/overview.component.ts
  frontend/src/app/admin/polls/poll-answer-detail/poll-answer-detail.component.html
  frontend/src/app/admin/polls/poll-answer-detail/poll-answer-detail.component.ts
  frontend/src/app/admin/polls/polls.component.html
  frontend/src/app/admin/polls/polls.component.ts
  frontend/src/app/admin/users/users.component.html
  frontend/src/app/admin/users/users.component.ts
  frontend/src/app/edit-create-pages/create-poll/create-poll.component.ts
  frontend/src/app/edit-create-pages/edit-create-pages.module.ts
  frontend/src/app/edit-create-pages/edit-poll/edit-poll.component.html
  frontend/src/app/edit-create-pages/edit-user-permissions/edit-user-permissions.component.html
  frontend/src/app/edit-create-pages/edit-user-permissions/edit-user-permissions.component.ts
  frontend/src/app/edit-create-pages/edit-user/edit-user.component.ts
  frontend/src/app/icons/icons.module.ts
  frontend/src/app/interfaces/organization.interface.ts
  frontend/src/app/interfaces/poll.interface.ts
  frontend/src/app/interfaces/user.interface.ts
  frontend/src/app/login-register/create-org/create-org.component.html
  frontend/src/app/login-register/create-org/create-org.component.ts
  frontend/src/app/login-register/login-register.module.ts
  frontend/src/app/login-register/login-register.routes.ts
  frontend/src/app/login-register/register/register.component.html
  frontend/src/app/login-register/register/register.component.ts
  frontend/src/app/my-profile/my-profile.pages.ts
  frontend/src/app/services/current-org/current-org.service.ts
  frontend/src/app/services/data/data.service.ts
  frontend/src/app/services/data/organizations/organizations.service.ts
  frontend/src/app/services/data/polls/polls.service.ts
  frontend/src/app/services/data/users/users.service.ts
  frontend/src/app/ui/markdown-input/markdown-input.component.html
  frontend/src/app/ui/navbar/navbar.component.ts
  frontend/src/app/ui/poll/poll.component.html
  frontend/src/app/ui/poll/poll.component.ts
  frontend/src/app/ui/progress-bar/progress-bar.component.html
  frontend/src/app/ui/progress-bar/progress-bar.component.ts
  frontend/src/app/ui/top-bar/top-bar.component.html
  frontend/src/app/ui/top-bar/top-bar.component.ts
  frontend/src/app/ui/ui.module.ts
  server/src/api/v1/users/get-users.ts
  server/src/interfaces/organization.interface.ts
  server/src/migrations/20210214140025-update-org.js
  server/src/migrations/20210214221603-update-org.js
  server/src/models/organization.model.ts
  server/src/models/user.model.ts
Labels: portal/frontend

#173 Public Team
  frontend/src/app/edit-create-pages/create-event/create-event.component.html
  frontend/src/app/edit-create-pages/create-event/create-event.component.ts
  frontend/src/app/edit-create-pages/edit-event/edit-event.component.html
  frontend/src/app/edit-create-pages/edit-event/edit-event.component.ts
  frontend/src/app/edit-create-pages/edit-poll/edit-poll.component.ts
  frontend/src/app/interfaces/event.interface.ts
  server/src/api/v1/users/create-user.ts
  server/src/api/v2/event-registrations/register-for-event.ts
  server/src/api/v2/event-registrations/register-for-public-event.ts
  server/src/api/v2/events/delete-event.ts
  server/src/api/v2/events/get-events.ts
  server/src/api/v2/events/get-public-events.ts
  server/src/api/v2/events/update-event.ts
  server/src/api/v2/organizations/create-organization.ts
  server/src/api/v2/poll-votes/create-poll-vote.ts
  server/src/api/v2/polls/get-polls.ts
  server/src/api/v2/teams/get-teams.ts
  server/src/functions/load-decoded-token-from-header.func.ts
  server/src/functions/map-org.func.ts
  server/src/interfaces/event.interface.ts
  server/src/interfaces/organization.interface.ts
  server/src/migrations/20210215125726-update-org.js
  server/src/migrations/20210215142409-update-event.js
  server/src/models/event.model.ts
  server/src/models/organization.model.ts
  server/src/models/poll.model.ts
  server/src/models/team.model.ts
  server/src/server.ts
Labels: portal/backend, portal/frontend

#176 Backend/export data
  server/src/api/v1/admin/export-direct-debit-mandates.ts
  server/src/api/v1/admin/export-event-registrations.ts
  server/src/api/v1/admin/export-users.ts
  server/src/models/direct-debit-mandate.model.ts
  server/src/server.ts
Labels: portal/backend

#180 Backend: Last Login / Event Log
  server/src/api/v1/users/auth-user.ts
  server/src/api/v2/event-logs/get-event-logs.ts
  server/src/bootstrap/connect-db.func.ts
  server/src/interfaces/event-log.interface.ts
  server/src/interfaces/users.interface.ts
  server/src/migrations/20210216104652-update-user.js
  server/src/migrations/20210216145025-create-event-log.js
  server/src/models/direct-debit-mandate.model.ts
  server/src/models/event-log.model.ts
  server/src/models/event-registration.model.ts
  server/src/models/event.model.ts
  server/src/models/logged.model.ts
  server/src/models/membership.model.ts
  server/src/models/news.model.ts
  server/src/models/organization.model.ts
  server/src/models/poll-answer.model.ts
  server/src/models/poll-vote.model.ts
  server/src/models/poll.model.ts
  server/src/models/role-assignment.model.ts
  server/src/models/role.model.ts
  server/src/models/team.model.ts
  server/src/models/user.model.ts
  server/src/server.ts
Labels: portal/backend

#181 Backend: Change length of Event description to 10000 chars
  server/src/migrations/20210216225929-update-event.js
Labels: portal/backend

#162 meeting protocol & texte für die Abschlusspräsentation
  documentation/meetings/2021-02-11.md
  documentation/presets/event1.md
  documentation/presets/event2.md
  documentation/presets/news1.md
  documentation/presets/news2.md
  documentation/presets/poll1.md
  documentation/presets/poll2.md
Labels: documentation

#179 Maintainer can update team
  server/src/api/v2/teams/update-team.ts
  server/src/server.ts
Labels: portal/backend

#182 Error handling
  server/.eslintrc.json
  server/package-lock.json
  server/package.json
  server/src/api/v1/users/auth-user.ts
  server/src/api/v2/documents/get-documents.ts
  server/src/api/v2/event-registrations/delete-event-registration.ts
  server/src/api/v2/event-registrations/update-event-registration.ts
  server/src/api/v2/events/get-events.ts
  server/src/api/v2/organizations/create-organization.ts
  server/src/api/v2/poll-votes/create-poll-vote.ts
  server/src/api/v2/polls/get-polls.ts
  server/src/api/v2/teams/create-team.ts
  server/src/api/v2/teams/delete-team.ts
  server/src/enum/errors.ts
  server/src/functions/load-decoded-token-from-header.func.ts
  server/src/functions/map-teams.func.ts
  server/src/functions/map-users.func.ts
  server/src/functions/query-builder.func.ts
  server/src/interfaces/error-handler-interface.ts
  server/src/middleware/error-handler.ts
  server/src/middleware/user-is-admin.middleware.ts
  server/src/middleware/user-is-authorized.middleware.ts
  server/src/models/event.model.ts
  server/src/models/organization.model.ts
  server/src/models/poll-answer.model.ts
  server/src/models/poll.model.ts
  server/src/models/role.model.ts
  server/src/models/team.model.ts
  server/src/models/user.model.ts
  server/src/server.ts
  server/tsconfig.json
Labels: portal/backend

#191 Backend: Hotfix getOrganization permission
  server/src/api/v2/organizations/get-organizations.ts
Labels: portal/backend

#196 datenschutzerklaerung.md
  documentation/presets/datenschutzerklaerung.md
Labels: documentation

#197 added new Meeting Protocoll
  documentation/meetings/2021-02-19.md
Labels: documentation
