Repository ToKoSoftware/dhbw-svm-portal, pull requests merged in 2021-01, with the labels that each got.

#19 Added previous meeting protocols
  documentation/meetings/2020-12-01
  documentation/meetings/2020-12-01.md
  documentation/meetings/2020-12-14
  documentation/meetings/2020-12-14.md
  documentation/meetings/2020-12-15
  documentation/meetings/2020-12-15.md
  documentation/meetings/2021-01-05
  documentation/meetings/2021-01-05.md
Labels: documentation

#28 Add nginx-reverse-proxy docker configuration
  docker-compose-reverse-proxy.yml
  docker-compose.yml
Labels: portal/backend

#27 Backend Models
  server/package-lock.json
  server/package.json
  server/src/api/v1/admin/get-stats.ts
  server/src/api/v1/users/auth-user.ts
  server/src/api/v1/users/create-user.ts
  server/src/api/v1/users/get-users.ts
  server/src/api/v1/users/update-user.ts
  server/src/bootstrap/connect-db.func.ts
  server/src/functions/jwt-sign.func.ts
  server/src/functions/map-users.func.ts
  server/src/functions/verify-token.func.ts
  server/src/interfaces/event.interface.ts
  server/src/interfaces/news.interface.ts
  server/src/interfaces/organization.interface.ts
  server/src/interfaces/poll-answer.interface.ts
  server/src/interfaces/poll.interface.ts
  server/src/interfaces/role.interface.ts
  server/src/interfaces/team.interface.ts
  server/src/interfaces/users.interface.ts
  server/src/migrations/20210111002620-create-user-and-organization.js
  server/src/migrations/20210111233320-create-events.js
  server/src/migrations/20210112000734-create-event-registrations.js
  server/src/migrations/20210112002756-create-news.js
  server/src/migrations/20210112114502-create-polls.js
  server/src/migrations/20210112120545-create-poll-answer.js
  server/src/migrations/20210112121434-create-poll-vote.js
  server/src/migrations/20210112122606-create-teams.js
  server/src/migrations/20210112123749-create-memberships.js
  server/src/migrations/20210112124407-create-roles.js
  server/src/migrations/20210112125523-create-role-assignments.js
  server/src/models/event-registration.model.ts
  server/src/models/event.model.ts
  server/src/models/membership.model.ts
  server/src/models/news.model.ts
  server/src/models/organization.model.ts
  server/src/models/poll-answer.model.ts
  server/src/models/poll-vote.model.ts
  server/src/models/poll.model.ts
  server/src/models/role-assignment.model.ts
  server/src/models/role.model.ts
  server/src/models/team.model.ts
  server/src/models/user.model.ts
  server/src/seeders/20210103140024-demo-admin-user.js
  server/src/seeders/20210111120513-demo-data-set.js
  server/src/vars.ts
Labels: portal/backend

#30 Add input validation to generic input field implementation
  frontend/src/app/admin/overview/overview.component.html
  frontend/src/app/edit-create-pages/edit-user/edit-user.component.ts
  frontend/src/app/login-register/login-register.module.ts
  frontend/src/app/login-register/login/login.component.html
  frontend/src/app/login-register/login/login.component.ts
  frontend/src/app/login-register/register/register.component.ts
  frontend/src/app/my-profile/credentials/my-credentials.component.html
  frontend/src/app/my-profile/credentials/my-credentials.component.ts
  frontend/src/app/ui/input/input.component.html
  frontend/src/app/ui/input/input.component.ts
Labels: portal/frontend

#32 Backend: Fix updateUser response bug
  server/src/api/v1/users/auth-user.ts
  server/src/api/v1/users/update-user.ts
Labels: portal/backend

#29 Validation and Scopes on Models
  server/src/migrations/20210113150210-fix-poll-vote.js
  server/src/models/event-registration.model.ts
  server/src/models/event.model.ts
  server/src/models/membership.model.ts
  server/src/models/news.model.ts
  server/src/models/organization.model.ts
  server/src/models/poll-answer.model.ts
  server/src/models/poll-vote.model.ts
  server/src/models/poll.model.ts
  server/src/models/role-assignment.model.ts
  server/src/models/role.model.ts
  server/src/models/team.model.ts
  server/src/models/user.model.ts
Labels: portal/backend

#56 Documenation: ER model
  documentation/er_model/ER.dia
  documentation/er_model/ER.png
Labels: documentation

#57 Implemented news page
  frontend/src/app/admin/users/users.component.html
  frontend/src/app/edit-create-pages/edit-user/edit-user.component.ts
  frontend/src/app/home/home/home.component.html
  frontend/src/app/interfaces/user.interface.ts
  frontend/src/app/services/login/login.service.ts
  frontend/src/app/ui/card/card.component.html
  frontend/src/app/ui/card/card.component.ts
  frontend/src/app/ui/header/header.component.html
  frontend/src/app/ui/navbar/navbar.component.html
  frontend/src/app/ui/news/news.component.html
  frontend/src/app/ui/scroll/scroll.component.html
  frontend/src/app/ui/scroll/scroll.component.ts
  frontend/src/app/ui/ui.module.ts
Labels: portal/frontend

#59 Backend: Add org_id to jwtSign
  server/src/functions/jwt-sign.func.ts
Labels: portal/backend

#61 Backend: Teams read api
  server/src/api/v1/users/auth-user.ts
  server/src/api/v1/users/get-users.ts
  server/src/api/v2/teams/get-teams.ts
  server/src/functions/query-builder.func.ts
  server/src/functions/verify-token.func.ts
  server/src/models/user.model.ts
  server/src/server.ts
Labels: portal/backend

#64 ADD:meeting protocol 2021-01-14
  documentation/meetings/2021-01-14.md
Labels: documentation

#65 Reimplement layout
  frontend/src/app/admin/users/users.component.html
  frontend/src/app/admin/users/users.component.ts
  frontend/src/app/app.component.html
  frontend/src/app/events/events.module.ts
  frontend/src/app/events/overview/overview.component.html
  frontend/src/app/home/home/home.component.html
  frontend/src/app/ui/card/card.component.html
  frontend/src/app/ui/container/container.component.ts
  frontend/src/app/ui/filter/filter.component.html
  frontend/src/app/ui/navbar/navbar.component.html
  frontend/src/app/ui/navbar/navbar.component.ts
  frontend/src/app/ui/scroll/scroll.component.html
  frontend/src/app/ui/scroll/scroll.component.ts
  frontend/src/app/ui/secondary-navigation/secondary-navigation.component.html
  frontend/src/app/ui/secondary-navigation/secondary-navigation.component.ts
  frontend/src/styles.scss
Labels: portal/frontend

#66 Backend: Fix create and update user
  server/src/api/v1/users/create-user.ts
  server/src/api/v1/users/update-user.ts
  server/src/models/user.model.ts
Labels: portal/backend

#69 ADD: Meeting-Protkoll-22-01-2021
  documentation/meetings/2020-12-01
  documentation/meetings/2020-12-14
  documentation/meetings/2020-12-15
  documentation/meetings/2021-01-05
  documentation/meetings/2021-01-14.md
  documentation/meetings/2021-01-22.md
Labels: documentation

#93 READ_API
  server/src/api/v2/events/get-events.ts
  server/src/api/v2/news/get-news.ts
  server/src/api/v2/organizations/get-organizations.ts
  server/src/api/v2/polls/get-polls.ts
  server/src/api/v2/roles/get-roles.ts
  server/src/seeders/20210111120513-demo-data-set.js
  server/src/seeders/20210126145413-demo-not-admin.js
  server/src/server.ts
Labels: portal/backend

#100 Backend: Create Api for Teams
  server/src/api/v2/teams/create-membership.ts
  server/src/api/v2/teams/create-team.ts
  server/src/functions/map-membership.func.ts
  server/src/functions/map-teams.func.ts
  server/src/interfaces/membership.interface.ts
  server/src/interfaces/team.interface.ts
  server/src/interfaces/users.interface.ts
  server/src/models/membership.model.ts
  server/src/models/team.model.ts
  server/src/server.ts
  server/src/vars.ts
Labels: portal/backend

#95 Backend: Create Api for Events
  server/src/api/v2/events/create-event.ts
  server/src/api/v2/events/register-for-event.ts
  server/src/functions/check-inputs.func.ts
  server/src/functions/map-event-registration.func.ts
  server/src/functions/map-events.func.ts
  server/src/interfaces/event-registration.interface.ts
  server/src/models/event-registration.model.ts
  server/src/models/event.model.ts
  server/src/server.ts
Labels: portal/backend

#94 Backend: Create Api for News
  server/src/api/v2/events/get-events.ts
  server/src/api/v2/news/create-news.ts
  server/src/functions/map-news.func.ts
  server/src/models/news.model.ts
  server/src/server.ts
Labels: portal/backend

#107 ADD: meeting protocol 2021-01-29
  documentation/meetings/2021-01-29.md
Labels: documentation

#108 Backend: Bugfixes
  server/src/api/v1/users/create-user.ts
  server/src/api/v1/users/update-user.ts
  server/src/interfaces/event.interface.ts
  server/src/migrations/20210113150210-fix-poll-vote.js
  server/src/migrations/20210120212212-fix-events-default-values.js
  server/src/migrations/20210130222914-fix-string-length.js
  server/src/models/event-registration.model.ts
  server/src/models/event.model.ts
  server/src/models/news.model.ts
  server/src/models/poll.model.ts
  server/src/seeders/20210126145413-demo-not-admin.js
Labels: portal/backend
